function createlegend(axes1)
%CREATELEGEND(axes1)
%  AXES1:  legend axes

%  Auto-generated by MATLAB on 29-Aug-2019 16:55:41

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.469808736522147 0.711888275819031 0.0619791656111676 0.174515230448732],...
    'FontWeight','bold',...
    'FontSize',15);

